# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c4d2e1265d7344336441ef6f8a1bbacf01df834164c2919e967a98b6d944926027f288af48428e6adff3f813d946370e514d3fe70c6d64c9d421c5cec65069c

test:
  secret_key_base: edec2c7a80b609819dea4e3ebeb5d8fcdf115bd5036c9c35e3e5a57b8f6ecada066a31c9a7614775ad3c36dbf5aaf4e36f59d3db543d2ed6be60dd9d683aa465

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
